name: Update Scholar Stats

on:
  workflow_dispatch:

permissions:
  contents: write        # ← allow GITHUB_TOKEN to push

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: main              # ← explicitly switch to the main branch
          persist-credentials: true
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run stats collection
        env:
          PROXY_USERNAME: ${{ secrets.PROXY_USERNAME }}
          PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}
          PROXY_SERVER:   ${{ secrets.PROXY_SERVER }}
          PROXY_PORT:     ${{ secrets.PROXY_PORT }}
          SCHOLAR_ID:     ${{ secrets.SCHOLAR_ID }}
        run: python scripts/get_scholar_stats.py

      - name: Debug file
        run: |
          ls -la data/
          cat data/scholar_stats.json || echo "missing"
      
      - name: Commit & push if changed
        run: |
          git config --global user.name  "GitHub Actions"
          git config --global user.email "actions@github.com"
      
          # Debug any changes in the file
          echo "Debugging changes before staging:"
          git diff data/scholar_stats.json || echo "No differences found"
      
          # Stage your JSON
          git add data/scholar_stats.json
      
          # If no changes staged, bail out
          if git diff --cached --quiet; then
            echo "✅ No changes to commit"
            exit 0
          fi
          
          # Fetch and merge the latest changes from the remote main branch
          git fetch origin
          git merge origin/main
      
          # Commit and push changes
          git commit -m "ci: update scholar stats data"
          git push origin main
      
